### ISSUE TITLE
有没有人知道怎么让所有人都能上传和下载TrsData文件

### ISSUE THREAD

**Issue by stevetrs** [stevetrs/mytrs1#1]
第一次用github，求告知，上传的人该怎么操作，我该怎么操作
我知道可以上传到代码里，但是代码好像不能单独下载某个文件，手动复制也不是很方便。

**Comment by Well54141660** [comment]
没有用github编辑过项目，不是很懂~

**Comment by imboaba** [comment]
已提交PR @stevetrs

**Comment by Well54141660** [comment]
不是很清楚，github没在上面写过项目~

imboaba ***@***.***> 于2023年5月11日周四 21:11写道：
