### ISSUE TITLE
希望能添加续翻功能

### ISSUE THREAD

**Issue by 1911san** [stevetrs/mytrs1#22]
我使用的是2.1封装版工具，翻译器只选择了80万额度的百度和新申请的彩云api（但是我在config里百度的额度没有改对，我是猪鼻）

在翻译一个130万日文字符的json的时候发现每次翻译都是拿ManualTransFile里的原文来输入翻译引擎里翻译的，这导致了尽管输出了repeat和untrsed，但不能通过手动翻译repeat和untrsed后并入第一次的结果中解决异常文本问题，在第二次翻译也会ManualTransFile里的原文并输出同样的repeat和untrsed，但是翻译额度被浪费了（悲）

我粗略看了几遍源码和使用说明，但并没有相关的内容，希望大佬日后有空能添加续翻功能：
在第一次翻译完成输出了repeat和untrsed后，在第二次翻译中选择只输入repeat和untrsed，根据其是否被完全翻译来决定是否输入到翻译器，最后把翻译结果并入到第一次的翻译结果

**Comment by 1911san** [comment]
不太清楚TrsData里每一条  **_"原文"="译文",_**  的排序是否会对mtool读取并把译文注入到游戏的过程产生问题，若不影响加载的话，貌似repeat和untrsed的问题在文本量比较小情况下都能手动修改后在TrsData里直接cv

**Comment by stevetrs** [comment]
没太看明白你的问题....
不过trsdata里的排序的确不会影响mtool的载入
在有设置backupengine的情况下，会自动翻译用backupengine翻译repeat文本，导出的repeat.json是在二次翻译后仍是异常的文本。手动翻译这些异常文本比较建议用不同的翻译引擎来重新翻译，相同的引擎翻译多次，结果大概率也是异常的。
至于untrsed，你把它改名成ManualTransFile就可以用工具来翻译了，不需要手动翻译。

**Comment by 1911san** [comment]
啊，我可能没有表达的特别清楚，具体来说，如果可能的话想大佬添加这样的功能：

1. 在有设置backupengine，且需要选择是否使用backupengine的时候，选择不使用backupengine也能够输出repeat和untrsed（目前好像是只能在选择使用backupengine的时候输出repeat和untrsed）；
2. 在工具里自行选择需要进行翻译的文件（免去untrsed改名的烦恼）；
3. 在选择一个文件后，若文件中每一条   **_"原文"="译文"_**   的译文部分没有日文字符，选择是否将该文件的   **_"原文"="译文"_**  内容并入TrsData，若译文部分存在日文字符则选择是否进行翻译（目前untrsed改名成ManualTransFile后继续用工具翻译，repeat则是我自己抽象听译）；
4. 翻译或译文并入TrsData完毕后，生成日志以记录已翻译和已并入TrsData的文件MD5。在选择文件进行翻译或并入TrsData的时候，根据文件的md5提示用户该文件是否已被翻译或已被并入TrsData（以免出现像我一样大文件翻译两次白给额度的猪鼻，也防止文件被二次并入TrsData）。

总的来说只是一些优化的小建议吧，大佬你有心情可以考虑整一下

> trsdata里的排序的确不会影响mtool的载入

那repeat和untrsed就是需要分别翻译再手动cv到trsdata里就好了，谢谢大佬

**Comment by stevetrs** [comment]
> 1. 在有设置backupengine，且需要选择是否使用backupengine的时候，选择不使用backupengine也能够输出repeat和untrsed（目前好像是只能在选择使用backupengine的时候输出repeat和untrsed）；

目前的设置是，在backupengine为空的时候，也会输出repeat文件，backupengine不为空的时候，则是遍历整个backupengine之后再输出repeat文件
而untrsed，和backupengine没有关系，只要是没有完整翻译整个文件，就会输出untrsed

> 2. 在工具里自行选择需要进行翻译的文件（免去untrsed改名的烦恼）；

有点麻烦，而且我没学过相关内容，在我目前有的知识范围内，能做到的只是在config.json内修改目标文件名，或者在控制台当场输入，这样反而更繁琐了。

> 3. 在选择一个文件后，若文件中每一条   **_"原文"="译文"_**   的译文部分没有日文字符，选择是否将该文件的   **_"原文"="译文"_**  内容并入TrsData，若译文部分存在日文字符则选择是否进行翻译（目前untrsed改名成ManualTransFile后继续用工具翻译，repeat则是我自己抽象听译）；

目前对于没有完整翻译整个文件的处理办法是，把未翻译的字符从trsdata中删掉，然后单独输出成untrsed。用户只需要单独再翻译一次untrsed，然后把两个文件合并即可。
感觉这个操作也不是很复杂，暂时没必要加入这个功能

> 4. 翻译或译文并入TrsData完毕后，生成日志以记录已翻译和已并入TrsData的文件MD5。在选择文件进行翻译或并入TrsData的时候，根据文件的md5提示用户该文件是否已被翻译或已被并入TrsData（以免出现像我一样大文件翻译两次白给额度的猪鼻，也防止文件被二次并入TrsData）。

缺少MD5相关知识，看不懂这条建议(;´・`)>
